# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MShopKeeper' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 4.5'
  pod 'SQLite.swift', '~> 0.11.4'
  pod 'Kingfisher', '~> 4.0'
  pod "MTBBarcodeScanner"

  # Pods for MShopKeeper

  target 'MShopKeeperTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MShopKeeperUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
